'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
 import { useEffect } from 'react';
import Navbar from "../component/Navbar/navbar";
import Head from 'next/head'

import { Provider } from "react-redux";
import store from "@/redux/store";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap');
   
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
     

<Provider store={store}>
<Head>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
<link rel="manifest" href="/site.webmanifest"></link>  
    </Head>

        <Navbar/>
        {children}
</Provider>

   
     
      {/* <Footer/>     */}
        </body>
    </html>
  );
}
