'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
 import { useEffect } from 'react';
import Navbar from "../component/Navbar/navbar";


import { Provider } from "react-redux";
import store from "@/redux/store";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    import('bootstrap/dist/js/bootstrap');
   
  }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
     

<Provider store={store}>


        <Navbar/>
        {children}
</Provider>

   
     
      {/* <Footer/>     */}
        </body>
    </html>
  );
}
